---
title: "`r params$GameTitle` Game Design Document"
params:
  GameTitle: "Solara"
  GamePredator: "hero"
  GamePrey: "beasts" # decide whether to use beast, demon, monster, etc.
format: 
  html:
    toc: true
    toc-expand: true
    other-links: 
      - text: View on Github
        href: https://github.com/niboXR/first-game
        icon: github
      - text: Project tasks and timeline
        href: https://github.com/users/niboXR/projects/3
        icon: github
        class: no-icon
---

```{r, setup}
#| include: false
```

# Overview

## Game description

**`{r} params$GameTitle`** is a stylized open-globe action-adventure fantasy game with support for up to 64 simultaneous players and built from the ground up for physical immersion.

The world of `{r} params$GameTitle` falls increasingly to darkness. The residents have abandoned their homes for shelter within the last standing city of `{r} params$GameTitle`. The majority of the population has turned into mindless `{r} params$GamePrey`. You awaken as a resident of `{r} params$GameTitle`. Does the will of a `{r} params$GamePredator` or the will of `{r} params$GamePrey` awaken with you?

Take on the world alone or form an adventurer's guild in a fantastical, yet-dangerous, quest to eradicate darkness and retake `{r} params$GameTitle`. Explore the land to discover lost treasures, uncover knowledge, and unravel its mysteries. Master your trade or become a jack of all trades. You determine your path.

## Inspirations

No Mans Sky, while it took some time, eventually demonstrated the incredible power of procedural generation. Their implementation has resulted in a mind-bending sci-fi exploration game that has captivated me for hundreds of hours.

Zelda: Breathe of the Wild is an illustrious open-world action adventure game with some basic RPG elements. The simple, yet compelling style and mechanics contributes to a world that breathes.

OG virtual reality rpg games like Zenith: The Last City, Karnage Chronicles, and Vengeful Rites that first immersed me in fantasy worlds.

##### The goal is to learn from the successes and failures of early virtual reality games and apply the programming wizardry of procedural world-building in pursuit of infinite immersive worlds as compelling as Hyrule.

# Design

## Gameplay

The world is filled with distinct characters and environments that drive fresh quest opportunities. Dungeons and encampments can be taken down for experience and looted for treasure. Mastering a trade will prove valuable in the ultimate quest to defeat the world boss and restore the world's peace.

## Character

Characters are all humanoids that exist in the world, playable and non-playable. The following stats apply to both.

### Character stats

#### Physical stats

A character has three physical stats:

-   **Vitality** - determines how much damage a character can take. A character's base vitality stat is **100** life points.

-   **Strength** - determines how much damage a character can deal. A character's base strength stat is **10** damage. This means that a fully effective blow will deal **10** points in damage to another character's vitality or an item's durability.

-   **Speed** - determines how quickly a character can move. A character's base walking speed is **INSERT WLK_SPD** and base running speed is **INSERT RUN_SPD**.

These base values are adjusted slightly based on the character build [^1]. See @tbl-1 for a generalized overview of this system based on character BMI [^2]. Physical stats can be further modified via items and consumables.

[^1]: This design is inspired by Bonelab's avatar system and intended to incentivize thoughtful and diverse character creation.

[^2]: Body Mass Index is calculated from a person's height and weight. While this measure is considered imperfect for real-world applications, it provides a single measure from which base stats can be derived.

+-----------+----------+----------+---------+
| Character | Vitality | Strength | Speed   |
|           |          |          |         |
| BMI       |          |          |         |
+===========+==========+==========+=========+
| Low       | ➖       | 🔻       | 🔺      |
+-----------+----------+----------+---------+
| Med       | ➖       | ➖       | ➖      |
+-----------+----------+----------+---------+
| High      | 🔺       | 🔺       | 🔻🔻    |
+-----------+----------+----------+---------+

: Impact of BMI on character physical stats\
🔺stat boost ➖no change 🔻stat penalty {#tbl-1}

#### Standing

A character's standing indicates their threat and morality to others. The two standing stats are:

-   **Level** - an evolving measure of a character's accomplishments. It is derived from enemy encounter outcomes. A character's default and minimum level is **1**. The maximum level is **100**.

-   **Karma** - an evolving measure of a character's deeds. It is derived from your actions. The quests you take on, the enemies you kill, and even your environmental impact will dictate your place in this world. The default karma is **NEUTRAL**. Creating a world with karmic justice requires deep considerations for both the penalties and consequences. See @sec-justice on Karmic Justice for more.

### Character creation

### Character controller

## Environment

A procedural system for the creation of unique and infinitely difficult worlds[^3]. The globe is fully navigable with diverse landscapes, wildlife, and beasts.

[^3]: A procedural system combines parameters for switching between categorical values and random sampling for continuous values. Note that available parameters and probability curves will likely be impacted by other values.

### Resources

All resources can be gathered the environment. The resource types are:

-   **resources** - various types and qualities of wood, ore, and fibers

-   **ingredients** - various types and qualities of meat, fish, vegetation, and herbs

Resources can be gathered and crafted into items by characters engaging in various professions.

### Items

Items can be discovered throughout the world or crafted from resources gathered from the environment. The item types are:

-   **wearables** are crafted from resources by outfitters

-   **consumables** are crafted from ingredients by cooks and from resources by alchemists

-   **tools** are crafted from resources by toolmakers

Items have varying **durability** which can be restored by crafting professionals. Items can also be broken down for partial resources. Items can be carried between worlds and parallel world items are sometimes considered mystic[^4]. Item rarity is based on the reference world's items. See @tbl-2 below for rarity calculations.

[^4]: A parallel world is one whose environment produces any number of distinct resources and ingredients not available in the reference world. An item is considered mystic if it is located in a world without access to the resources it is crafted.

| Rarity    | Color  | Threshold                                      |
|-----------|--------|------------------------------------------------|
| Common    | White  | The item makes up no more than 25% of its kind |
| Uncommon  | Green  | The item makes up less than 25% of its kind    |
| Rare      | Blue   | The item makes up less than 5% of its kind     |
| Legendary | Purple | The item makes up less than 1% of its kind     |
| Unique    | Gold   | The only item of its kind in the world         |

: Rarities\
see @sec-itemkinds on the kinds of items {#tbl-2}

## Economy

### Professions {#sec-professions}

There are various professions in resources gathering and crafting.

#### Gathering professions

The following professions are dedicated to the gathering of natural resources and ingredients from the environment:

-   Hunter

-   Fisher

-   Forager

-   Miner

-   Logger

#### Crafting professions

The following professions are dedicated to crafting items from resources gathered from the environment:

-   Outfitter

-   Toolmaker

-   Cook

-   Barkeep

-   Alchemist

### Trade

Resources and items can be traded between characters on the open market or privately. Historical sale prices are public record at the server level.

One currency, forever.

# Addendum

## Karmic Justice {#sec-justice}

A character's karma can range from **DARK** to **HERO**. Characters can also have **GOOD**, **BAD**, and **NEUTRAL** karma. A character's karma can be positively impacted through the completion of hero quests. More importantly, karma penalties are levied for various misdeeds and the consequences bad karma can be steep.

### Karmic penalties

-   Character killing and looting
-   Dark quests
-   Resource overconsumption and waste

### Karmic consequences

-   Loss of safe zone and housing
-   Beast deformation?
-   Increased drop rates
-   Bounties

## The types and kinds of items {#sec-itemkinds}

This flowchart describes the types and kinds of items and provides some examples of items that may or not be present in the final game.

```{mermaid}
flowchart LR
ITEMS[(ITEMS)] --> Wearable
ITEMS --> | The types of items | Consumable
ITEMS --> Tool

KindsOfWearables["`headwear
    topwear
    legwear
    footwear`"]
Wearable --> KindsOfWearables

KindsOfConsumables["`food
  drink
  elixer
`"]
Consumable --> |The kinds of items| KindsOfConsumables

KindsOfTools["`sword
  shield
  fishing pole
  pickaxe
  axe`"]
Tool --> KindsOfTools

ExampleWearables["`
  brass helmet
  dark tunic
  leather pants
  leather boots
`"]
  
KindsOfWearables --> ExampleWearables

ExampleConsumables["`
  beef stew
  elixer of life
`"]

KindsOfConsumables --> |some examples of items|ExampleConsumables

ExampleTools["`
  long sword
  wooden shield
  bamboo fishing pole
  iron pickaxe
  stone axe
`"]

KindsOfTools --> ExampleTools


```

## Documentation

### Definitions

#### Lived experiences {#sec-lived}

{{< include documentation/definitions/lived-experiences.md >}}
