---
title: "Game Design Document"
format: html
---

# Overview

## Mission and Vision

The vision is to create a world sized sanctuary you can share; a safe digital space to find comfort, excitement, and joy in solitude or alongside your people.

The mission is to redefine our lived experiences by creating a digital world that fosters experiences as meaningful as the ones from the physical world.

## Game description

**INSERT WORKING TITLE** is a open-globe action adventure game with support for up to 64 simultaneous players and built from the ground up for physical immersion.

## Inspirations

No Mans Sky

Zelda BOTW

Zenith: The Last City, Karnage Chronicles, Vengeful Rites

So much anime

# Design

## Character

### Character stats

#### Physical stats

A character has three physical stats:

-   **Vitality** - determines how much damage a character can take. A character's base vitality stat is **100** life points.

-   **Strength** - determines how much damage a character can deal. A character's base strength stat is **10** damage. This means that a fully effective blow will deal **10** points in damage to another character's vitality or an item's durability.

-   **Speed** - determines how quickly a character can move. A character's base walking speed is **INSERT WLK_SPD** and base running speed is **INSERT RUN_SPD**.

These base values are adjusted slightly based on the character build [^1]. See Table 1 for a generalized overview of this system based on character BMI [^2].

[^1]: This design is inspired by Bonelab's avatar system and intended to incentivize thoughtful and diverse character creation.
[^2]: Body Mass Index is calculated from a person's height and weight. While this measure is considered imperfect for real-world applications, it provides a single measure from which base stats can be derived. 


**Table 1. Impact of BMI on character physical stats**

___

+-----------+----------+----------+----------+
| Character | Vitality | Strength | Speed    |
|           |          |          |          |
| BMI       |          |          |          |
+===========+==========+==========+==========+
| Low       | ➖       | 🔻       | 🔺       |
+-----------+----------+----------+----------+
| Med       | ➖       | ➖       | ➖       |
+-----------+----------+----------+----------+
| High      | 🔺       | 🔺       | 🔻🔻     |
+-----------+----------+----------+----------+

: 🔺stat boost ➖no change 🔻stat penalty




Physical stats can be further modified by items and consumables.


#### Standing

## Environment
